### ISSUE TITLE
GitHub: feature request: allow adding announce for all repositories which the user has.

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Supybot-plugins#168]
It would be nice with personal channels.

```
+github announce add Mkaysi *
```

or

```
+github announce add Mkaysi --all
```

And this would make the bot announce everything related to those repositories as soon as the hooks were added.

**Comment by GLolol** [comment]
Per ead1a324da528c7c37436b8f207ffd980373d64e, you should be able to use globs like `*` in announce add. This was a previously undocumented feature.
