### ISSUE TITLE
GitHub: add support for secret

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Supybot-plugins#230]
If secret was supported, the plugin wouldn't need to have GitHub IP addresses hardcoded and could work with other services which use GitHub-like hooks. I am not sure if these exists, but Identica has Twitter-like API and Libravatar has Gravatar-like API.

* https://developer.github.com/webhooks/#events
* https://developer.github.com/v3/repos/hooks/#create-a-hook

It would also solve issue of needing plugin update after GitHub IPs change (I think this has happened at least once) or when they enable IPv6 which many users have been asking for (https://github.com/github/github-services/issues/489).

**Comment by ProgVal** [comment]
Implemented in 2130c5ba9bf58e6a2253822ee3c0a2cb562d74bd.
