### ISSUE TITLE
GitHub: allow specifying additional GitHub servers

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Supybot-plugins#246]
I am running Limnoria behind reverse proxy and Limnoria doesn't take the real IP from proxy which results to error "You are not GitHub server."

Releated: https://github.com/ProgVal/Limnoria/issues/894

**Comment by ProgVal** [comment]
Closed by 2130c5ba9bf58e6a2253822ee3c0a2cb562d74bd, which implements #230
