### ISSUE TITLE
GitHub: Travis status is not shown correctly

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Supybot-plugins#274]
```
2015-04-15 00:02:00+0300 <@Dysforia> Mikaela/mikaela.github.io: Status for commit pages/channel: add swearing & slurs by Mikaela Suomalainen: The Travis CI build is in progress $target_url__tiny
````

`$target_url__tiny` should possibly be something else like URL where to find Travis status for the commit.

**Comment by ProgVal** [comment]
ping @w1sht0l1v3

**Comment by w1sht0l1v3** [comment]
Was this working before yesterday?If yes,try this: https://github.com/w1sht0l1v3/Supybot-plugins/commit/f1d045729806e8dd462cdea288a594470c87e752
It's just a work in progres..GitHub plugin needs someone to fully fix it.

**Comment by Mikaela** [comment]
I have no idea when it broke as it was working when I left Limnoria and yesterday when I set up the plugin with defaults it was broken. I am also not interested in taking random patches outside of the repository.

**Comment by nyuszika7h** [comment]
Fixed by 979edb.
