### ISSUE TITLE
2015-06-29 12:12:00+0300 <@Dysforia> Error: Unknown exception importing twitter: SyntaxError('invalid syntax', ('/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugins/Twitter/twitter.py', 52, 24, '      raise ImportError, "Unable to load a json library"\n'))

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Supybot-plugins#283]
Logs:

> INFO 2015-06-29T12:12:00 supybot load called on X by "Mikaela!mikaela@unaffiliated/mikaela".`

**Comment by Mikaela** [comment]
Oh, this is result of `load Twitter` and

> The current (running) version of this Supybot is 0.83.4.1+limnoria 2015.05.23, running on Python 3.4.3 (default, May 28 2015, 07:36:29)  [GCC 4.2.1 Compatible Debian Clang 3.0 (tags/RELEASE_30/final)].  The newest versions available online are 2015.06.28 (in testing), 2015.05.23 (in master).

**Comment by ProgVal** [comment]
This is a bug in Python-Twitter.

**Comment by ProgVal** [comment]
Not a bug, actually. It's just it doesn't support Python 3.
