### ISSUE TITLE
LinkRelay doesn't relay lines from the bot itself

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Supybot-plugins#288]
This affects at least `network command ircnet ircquote privmsg #channel hi`.

I believe the bot should also relay all the lines it sends including notices (`supybot.reply.withnotice`) as it looks stupid if another side of relay calls `wiki linux` and the other side doesn't see it.

**Comment by GLolol** [comment]
Using `ircquote` makes the bot send raw commands, which bypasses the usual `outFilter` catching that plugins use to control outbound messages. Does running `echo hi` work? (I don't remember, I haven't used stock LinkRelay for a while.)

**Comment by Mikaela** [comment]
I cannot test echo at the moment, but `command ircnet anonymous say #channel test` doesn't work either.

**Comment by Mikaela** [comment]
Echo has now been tested. The other side of the relay sees me calling echo but not the echo which is only visible on the side where the command was called.

`supybot.reply.withnotice` is `True`.

**Comment by GLolol** [comment]
So the issue is just that Notices aren't relayed? RelayBot in `#supybot` uses LinkRelay and the bot relays its own PRIVMSGs fine.

**Comment by Mikaela** [comment]
The issue is that nothing my bot says is relayed by itself. It uses notices like the RFC says (<https://tools.ietf.org/html/rfc1459#section-4.4.2>).

I also just tested Anonymous and it ignores `reply.withnotice` and uses PRIVMSG and as I said on https://github.com/ProgVal/Supybot-plugins/issues/288#issuecomment-133778314 it's not relayed either, so I wouldn't say only notices.

**Comment by GLolol** [comment]
Do PRIVMSGs work without `network command`? It could be related to ProgVal/Limnoria#556 if so.

**Comment by Mikaela** [comment]
I am not sure what you mean. It cannot be related to https://github.com/ProgVal/Limnoria/issues/556 because the channel is #channel on both networks and if it was https://github.com/ProgVal/Limnoria/issues/556 I should see the PRIVMSG on the same network where I am on and give the `network command` command.

**Comment by Mikaela** [comment]
Amusingly `cmdall announce` was relayed.

**Comment by Mikaela** [comment]
Closing in favour of https://github.com/ProgVal/Supybot-plugins/issues/317 .
