### ISSUE TITLE
We couldn’t deliver this payload: Service Timeout

### ISSUE THREAD

**Issue by ashwinidesh** [ProgVal/Supybot-plugins#315]
Got "We couldn’t deliver this payload: Service Timeout" even after setting up the Webhooks in Github.

Also, the Jenkins shows below error as shown in snapshot.

![image](https://cloud.githubusercontent.com/assets/25241367/22250995/2e92a6ae-e26f-11e6-92cb-63f68b8beded.png)

**Comment by nyuszika7h** [comment]
Have you tried redelivering the payload? And make sure there isn't a firewall blocking the connection.

(Also, that message on the picture looks like it was written by someone who is not very good at English.)

**Comment by ProgVal** [comment]
Is this issue related to one of the plugins in my repo?

**Comment by ashwinidesh** [comment]
Logging error
