### ISSUE TITLE
EchoTyping: when two bots have it enabled they detect each other typing and never stop typing

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Supybot-plugins#343]

**Comment by Mikaela** [comment]
I stopped being able to reproduce this on both the original network and testnet.ergo.chat.

**Comment by ProgVal** [comment]
that's a valid issue though

**Comment by Mikaela** [comment]
https://github.com/ProgVal/Supybot-plugins/commit/3f4348c86c4684f85e7e5e6aa488301ab434fcf4
